services:
    baota:
        image: vscwjm/baota:ncloud
        privileged: true
        restart: always
        stdin_open: true
        tty: true
        ports:
          - 80:80
          - 81:81
          - 443:443
          - 888:888
          - 2000:2000
          - 8888:8888
        volumes:
          - config:/mnt/config

    openwrt:
        image: sulinggg/openwrt:x86_64
        privileged: true
        restart: always
        stdin_open: true
        ports:
          - 80:80
          - 443:443
          - 3000:3000
          - 5299:5299
          - 6800:6800
          - 7681:7681
          - 8081:8081
          - 8088:8088
          - 19999:19999
          - 52657:52657
          - 54365:54365
          - 42981:42981
        volumes:
          - config:/mnt/config
        command: /sbin/init

volumes:
    config:
