services:
    baota:
        image: vscwjm/baota:ncloud
        privileged: true
        restart: always
        stdin_open: true
        tty: true
        ports:
          - 80:80
          - 81:81
          - 443:443
          - 888:888
          - 2000:2000
          - 8888:8888
        volumes:
          - aria2:/mnt/aria2
          - download:/mnt/download
          - cloudreve:/mnt/cloudreve
          
    aria2: 
        image: p3terx/aria2-pro
        logging: 
            options: 
                max-size: 1m
        ports: 
            - 6800:6800
            - 6888:6888
            - 6888:6888/udp
        environment: 
            - PUID=0
            - PGID=0
            - RPC_SECRET=wangjm0529..
        volumes: 
            - aria2:/config
            - download:/downloads
        restart: unless-stopped

    cloudreve: 
        image: xavierniu/cloudreve
        environment: 
            - PUID=0
            - PGID=0
        ports:
            - 5212:5212
        volumes: 
            - cloudreve:/cloudreve
            - download:/downloads
        restart: unless-stopped

volumes:
    download:
    cloudreve:
    aria2:
