services:
    caddy: 
        image: nginx:alpine
        ports: 
            - 80:80
            - 443:443
        volumes: 
            - nginx:/etc/nginx
        restart: unless-stopped
    
    aria2: 
        image: p3terx/aria2-pro
        logging: 
            options: 
                max-size: 1m
        ports: 
            - 6800:6800
            - 6888:6888
            - 6888:6888/udp
        environment: 
            - PUID=0
            - PGID=0
            - RPC_SECRET=wangjm0529..
        volumes: 
            - aria2:/config
        restart: unless-stopped
        
    cloudreve: 
        image: xavierniu/cloudreve
        environment: 
            - PUID=0
            - PGID=0
        volumes: 
            - cloudreve_config:/cloudreve
      
volumes:
  cloudreve_config:
  aria2:
  nginx:
