services:
  baota:
    image: vscwjm/baota:ncloud
    privileged: true
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 80:80
      - 81:81
      - 443:443
      - 888:888
      - 2000:2000
      - 8888:8888
    volumes:
      - rootpath:/mnt/rootpath
      - cloudreve_config:/mnt/cloud
      
volumes:
  rootpath:
  cloudreve_config:
